version: "3.9"

services:
  java_app:
    container_name: java_app
    image: pee-java_app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://172.31.7.122:5445/postgres
      - DATABASE_USERNAME=odoo_db
      - DATABASE_PASSWORD=odoo_db
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo_db
      - POSTGRES_USER=odoo_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5446:5432"
    # volumes:
    #   - odoo-db-data:/var/lib/postgresql/data/pgdata
# volumes:
#   odoo-db-data:
#   odoo-web-data: